# This file was generated by GoReleaser. DO NOT EDIT.
class Kr8 < Formula
  desc "Opinionated configuration management tool for Kubernetes Cluster"
  homepage "https://kr8.rocks"
  url "https://github.com/apptio/kr8/releases/download/v0.1.1/kr8_0.1.1_darwin_amd64.tar.gz"
  version "0.1.1"
  sha256 "76d8f364d41619df16aa35cb6a20d2f3322475d3598d4be33f15ec091e4f3d47"
  
  depends_on "kubernetes-helm"
  depends_on "jsonnet"
  depends_on "go-task/tap/go-task"

  def install
    bin.install "kr8"
    bin.install "scripts/kr8-helpers"
  end
end
