# This file was generated by GoReleaser. DO NOT EDIT.
class Kr8 < Formula
  desc "Opinionated configuration management tool for Kubernetes Cluster"
  homepage "https://kr8.rocks"
  version "0.1.2"

  if OS.mac?
    url "https://github.com/apptio/kr8/releases/download/v0.1.2/kr8_0.1.2_darwin_amd64.tar.gz"
    sha256 "12abe0f6f1ec149b539ccba9182edaf0115bd0c80ec89eedcdf740005af7c0b1"
  elsif OS.linux?
    url "https://github.com/apptio/kr8/releases/download/v0.1.2/kr8_0.1.2_linux_amd64.tar.gz"
    sha256 "ecc3ac7d06a546c2cc0417cc65593885c674ce627c7a12eb13696cb498ada391"
  end
  
  depends_on "kubernetes-helm"
  depends_on "jsonnet"
  depends_on "go-task/tap/go-task"

  def install
    bin.install "kr8"
    bin.install "scripts/kr8-helpers"
  end
end
