# This file was generated by GoReleaser. DO NOT EDIT.
class Kr8 < Formula
  desc "Opinionated configuration management tool for Kubernetes Cluster"
  homepage "https://kr8.rocks"
  version "0.2.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/apptio/kr8/releases/download/v0.2.5/kr8_0.2.5_darwin_amd64.tar.gz"
    sha256 "869c131e54ac7fbaa07bb9f880068204b726641d02936a970b25ea2a7423fd27"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/apptio/kr8/releases/download/v0.2.5/kr8_0.2.5_linux_amd64.tar.gz"
      sha256 "cf03f10c5a203fa6727fca96749a8e31ce194a54e6bb823a47bd75eaa03984b0"
    end
  end
  
  depends_on "kubernetes-helm"
  depends_on "jsonnet"
  depends_on "go-task/tap/go-task"

  def install
    bin.install "kr8"
    bin.install "scripts/kr8-helpers"
  end
end
