# This file was generated by GoReleaser. DO NOT EDIT.
class KubeConfig < Formula
  desc "Opinionated configuration management tool for Kubernetes Cluster"
  homepage "https://apptio.com"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/apptio/kube-config/releases/download/0.4.0/kube-config_0.4.0_darwin_amd64.tar.gz"
    sha256 "07413c23b5ae31176d1b60bbb4ef7ea01247c33f87dc3d778a2e54cce18061fb"
  elsif OS.linux?
    url "https://github.com/apptio/kube-config/releases/download/0.4.0/kube-config_0.4.0_linux_amd64.tar.gz"
    sha256 "761a1350f5eb9b2cb7afdaf585194c7ac361ac843bd351b87ad6db615035d2a1"
  end

  def install
    bin.install "kube-config"
  end
end
