# This file was generated by GoReleaser. DO NOT EDIT.
class KubeConfig < Formula
  desc "Opinionated configuration management tool for Kubernetes Cluster"
  homepage "https://apptio.com"
  version "0.4.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/apptio/kube-config/releases/download/0.4.9/kube-config_0.4.9_darwin_amd64.tar.gz"
    sha256 "c3e766b0ab325dc45453b19e80bae3b7734000e3210592318d969f16262e98c0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/apptio/kube-config/releases/download/0.4.9/kube-config_0.4.9_linux_amd64.tar.gz"
      sha256 "3b6533adeed24235259fa781e23ef8b334ff9c46f718197720de253a73f0ad32"
    end
  end

  def install
    bin.install "kube-config"
  end
end
