# This file was generated by GoReleaser. DO NOT EDIT.
class KubeConfig < Formula
  desc "Opinionated configuration management tool for Kubernetes Cluster"
  homepage "https://apptio.com"
  version "0.4.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/apptio/kube-config/releases/download/0.4.7/kube-config_0.4.7_darwin_amd64.tar.gz"
    sha256 "d2af020ea531797ea7fbf75737b5fce8bbbecde74ce2d099c85f72d20f416dc9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/apptio/kube-config/releases/download/0.4.7/kube-config_0.4.7_linux_amd64.tar.gz"
      sha256 "a0a5365432316bc14447f712c86be11511f669c2106a16bf3a2a07c98a4b38b2"
    end
  end

  def install
    bin.install "kube-config"
  end
end
